# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tutorialsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(787, 328)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_change = QtWidgets.QLabel(Dialog)
        self.lbl_change.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_change.setObjectName("lbl_change")
        self.gridLayout.addWidget(self.lbl_change, 0, 0, 1, 2)
        self.lbl_img = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_img.sizePolicy().hasHeightForWidth())
        self.lbl_img.setSizePolicy(sizePolicy)
        self.lbl_img.setMinimumSize(QtCore.QSize(300, 0))
        self.lbl_img.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_img.setText("")
        self.lbl_img.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_img.setObjectName("lbl_img")
        self.gridLayout.addWidget(self.lbl_img, 0, 2, 1, 2)
        self.btn_last = QtWidgets.QPushButton(Dialog)
        self.btn_last.setObjectName("btn_last")
        self.gridLayout.addWidget(self.btn_last, 2, 0, 1, 1)
        self.btn_next = QtWidgets.QPushButton(Dialog)
        self.btn_next.setObjectName("btn_next")
        self.gridLayout.addWidget(self.btn_next, 2, 3, 1, 1)
        self.lbl_gesture = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(26)
        self.lbl_gesture.setFont(font)
        self.lbl_gesture.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gesture.setObjectName("lbl_gesture")
        self.gridLayout.addWidget(self.lbl_gesture, 2, 1, 1, 2)
        self.lbl_msg = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_msg.sizePolicy().hasHeightForWidth())
        self.lbl_msg.setSizePolicy(sizePolicy)
        self.lbl_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_msg.setObjectName("lbl_msg")
        self.gridLayout.addWidget(self.lbl_msg, 1, 0, 1, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "新手教程"))
        self.lbl_change.setText(_translate("Dialog", "change to vw"))
        self.btn_last.setText(_translate("Dialog", "<< 上一个"))
        self.btn_next.setText(_translate("Dialog", "下一个 >>"))
        self.lbl_gesture.setText(_translate("Dialog", "手势"))
        self.lbl_msg.setText(_translate("Dialog", "请模仿左侧视频做出手势"))
